name = "mergelskaul-haus"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "mergelskaul-haus"
database_id = "953b522f-2441-4c3f-86d9-8b3bd114c307"
